services:
  # --- LE MOTEUR (BASE DE DONNÉES) ---
  db_stage:
    build: .
    container_name: mysql_container_exercice
    environment:
      MYSQL_DATABASE: service_desk_db
      MYSQL_ROOT_PASSWORD: secure_stage_2026
    # On ajoute un volume pour ne pas perdre les données de MySQL
    volumes:
      - data:/var/lib/mysql

  # --- LA CARROSSERIE (SERVEUR WEB) ---
  web_stage:
    build: 
      context: .
      dockerfile: web/Dockerfile.web
    container_name: web_container_exercice
    restart: always
    ports:
      - "9999:80"
    # On ajoute un volume pour modifier ton code PHP sans redémarrer
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db_stage

  phpmyadmin:
    image: phpmyadmin
    container_name: pma_stage
    links:
      - db_stage:db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db_stage
      MYSQL_ROOT_PASSWORD: secure_stage_2026

# On doit déclarer le volume nommé ici
volumes:
  data:

 